### ISSUE TITLE
Liquid logo and icon distorted in osx and windows

### ISSUE THREAD

**Issue by domegabri** [greenaddress/elements#7]
### Description

The icon and the logo look distorted in Windows and macos versions

#### Steps to reproduce:

Start liquid-qt

### Expected behaviour
Icon showed as in Linux version

### Screenshots.

REMOVED AS NOT APPLICABLE

### Version

3.14.1.22 aff772d

**Comment by luke-jr** [comment]
This should already be fixed. Build 392c5efbd7a8bace67c66faa09857a65f48084ca

**Comment by domegabri** [comment]
Testing 2e82bda19c336d92873a403b788b0cd262600aa3

## macOS Mojave 10.14 

Logo is now visible but very big:

<img width="300" alt="screenshot 2019-02-27 at 10 26 43" src="https://user-images.githubusercontent.com/42006886/53481077-c0696880-3a7c-11e9-8d2d-4cd822e9ee1d.png">

Dock icon : 

<img width="65" alt="icon_dock_osx" src="https://user-images.githubusercontent.com/42006886/53498457-ad6b8e00-3aa6-11e9-8ea2-879f95985eda.png">

## Windows 10

The deskop icon here is blue. The logo in the splashscreen isn't distorted and is entirely visible

<img width="850" alt="windows10_icons" src="https://user-images.githubusercontent.com/42006886/53498518-beb49a80-3aa6-11e9-9832-2a825eeb41b1.png">






The colors don't match the blue liquid logo except for the desktop icon in Windows 10.

**Comment by greenaddress** [comment]
Seems the colors don't match the liquid color (see https://blockstream.com/liquid/ for example) do you need an updated image file from us or?

**Comment by luke-jr** [comment]
Is the macOS system in question HiDPI, or non-HiDPI? Does Bitcoin Core have the same issue? What about Core 0.14?

**Comment by luke-jr** [comment]
Fixed colour issue in 747be3c1bbff3217dc230691bc4d3ed44f78e049

**Comment by domegabri** [comment]
Now testing with 1164cc432a05fbd2a47f0b35d575f945935c3e3c
I still have the image size issue on a MacBook Pro 2017 with retina display.

This instead is the splashscreen seen from a MacBook air 2014 without retina display:

![macbookairliquid](https://user-images.githubusercontent.com/42006886/53559776-33411500-3b4b-11e9-8298-92550b49798a.png)

**Comment by luke-jr** [comment]
So with the retina...

> Does Bitcoin Core have the same issue? What about Core 0.14?

**Comment by domegabri** [comment]
I tried bitcoin core 0.14.3. couldn't find binary for 0.14 : 

<img width="489" alt="bitcoinqt0 14 3" src="https://user-images.githubusercontent.com/42006886/53768734-f6be4200-3ed9-11e9-8e3d-2d7a3bc7650e.png">

**Comment by RCasatta** [comment]
last version on osxretina

<img width="484" alt="schermata 2019-03-05 alle 17 58 38" src="https://user-images.githubusercontent.com/6470319/53824704-e4451680-3f74-11e9-885f-05f23057bab9.png">

with or without this patch https://github.com/RCasatta/elements/commit/c6cefaaf1f3af995f9a513dba1854b86472f938b

**Comment by greenaddress** [comment]
fixed in PR here https://github.com/Blockstream/liquid/pull/22
